apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: default
  labels:
    release: kube-prometheus-stack   # 이 레이블이 있어야 Prometheus가 이 ServiceMonitor를 인식함
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
